# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
